apiVersion: v1
kind: Namespace
metadata:
  name: chaos-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-framework-sa
  namespace: chaos-framework
  labels:
    app: chaos-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-framework-cr
  labels:
    app: chaos-framework
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","list","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-framework-crb
  labels:
    app: chaos-framework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-framework-cr
subjects:
  - kind: ServiceAccount
    name: chaos-framework-sa
    namespace: chaos-framework
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reducer
  namespace: chaos-framework
spec:
  selector:
    matchLabels:
      app: reducer
  template:
    metadata:
      labels:
        app: reducer
    spec:
      serviceAccountName: chaos-framework-sa
      containers:
        - name: reducer
          image: iskorotkov/chaos-reducer:v0.6.0
          env:
            - name: ARGO_SERVER
              value: argo-server.argo.svc:2746
---
apiVersion: v1
kind: Service
metadata:
  name: reducer
  namespace: chaos-framework
spec:
  selector:
    app: reducer
  ports:
    - name: web
      port: 8811
      targetPort: 8811
      protocol: TCP
  type: ClusterIP
